### Classe para modelar o problema

In [ ]:
import numpy as np

class SlidingPuzzle():
    def __init__(self, num_blocos):
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if estado[i, j] == elemento:
                    return i, j
        return None, None

    def verifica_estados(self, atual, objetivo):
        flag = True
        for i in range(self.num_blocos):
            if flag == False:
                break

            for j in range(self.num_blocos):
                if atual[i, j] != objetivo[i, j]:
                    flag = False;
                    break;

        return flag

    def expande_estado(self, atual):
        novos_estados = []
        linha, coluna = self._encontra_posicao(atual, 0)

        # Cima
        if linha > 0:
            novo_estado = np.copy(atual)
            nova_linha = linha - 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Baixo
        if linha < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_linha = linha + 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)


        # Esquerda
        if coluna > 0:
            novo_estado = np.copy(atual)
            nova_coluna = coluna - 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Direita
        if coluna < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_coluna = coluna + 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        return novos_estados


### BFS

In [ ]:
from queue import Queue

class BreadthFirstSearch():
    def __init__(self, problema):
        self.problema = problema

    def _verifica_visitado(self, estado, estados_visitados):
        for i in estados_visitados:
            if self.problema.verifica_estados(i, estado):
                return True
        return False

    def busca(self, inicio, fim):
        fila = Queue()
        fila.put(inicio)

        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0

        while not fila.empty():
            atual = fila.get()
            estados_visitados.append(atual)

            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
            else:
                cont_estados += 1
                print(f"Visitando #{cont_estados}")
                novos_estados = self.problema.expande_estado(atual)
                for i in novos_estados:
                    if not self._verifica_visitado(i, estados_visitados):
                        print(i)
                        fila.put(i)

        return solucao_encontrada, estados_visitados, cont_estados


### DFS

In [ ]:
from queue import LifoQueue

class DepthFirstSearch():
    def __init__(self, problema):
        self.problema = problema

    def _verifica_visitado(self, estado, estados_visitados):
        for i in estados_visitados:
            if self.problema.verifica_estados(i, estado):
                return True
        return False

    def busca(self, inicio, fim):
        fila = LifoQueue()
        fila.put(inicio)

        solucao_encontrada = False
        estados_visitados = []
        cont_estados = 0

        while not fila.empty():
            atual = fila.get()
            estados_visitados.append(atual)

            if self.problema.verifica_estados(atual, fim):
                solucao_encontrada = True
                break
            else:
                cont_estados += 1
                print(f"Visitando #{cont_estados}")
                novos_estados = self.problema.expande_estado(atual)
                for i in novos_estados:
                    if not self._verifica_visitado(i, estados_visitados):
                        print(i)
                        fila.put(i)

        return solucao_encontrada, estados_visitados, cont_estados


### Main

In [ ]:
problema = SlidingPuzzle(3)

start = np.matrix([[2, 8, 3],[1, 6, 4],[7, 0, 5]])
print(start, "\n************\n")

target = np.matrix([[1, 2, 3],[8, 0, 4],[7, 6, 5]])
print(target, "\n************\n")

bfs = DepthFirstSearch(problema)
solution,visited,steps = bfs.busca(start,target)
if solution:
    print('Solution found in %d steps!' % steps)
else:
    print('Solution not found!')



A saída de streaming foi truncada nas últimas 5000 linhas.
 [4 2 0]]
Visitando #12927
[[3 8 5]
 [1 7 0]
 [4 2 6]]
Visitando #12928
[[3 8 0]
 [1 7 5]
 [4 2 6]]
[[3 8 5]
 [1 0 7]
 [4 2 6]]
Visitando #12929
[[3 0 5]
 [1 8 7]
 [4 2 6]]
[[3 8 5]
 [1 2 7]
 [4 0 6]]
[[3 8 5]
 [0 1 7]
 [4 2 6]]
Visitando #12930
[[0 8 5]
 [3 1 7]
 [4 2 6]]
[[3 8 5]
 [4 1 7]
 [0 2 6]]
Visitando #12931
[[3 8 5]
 [4 1 7]
 [2 0 6]]
Visitando #12932
[[3 8 5]
 [4 0 7]
 [2 1 6]]
[[3 8 5]
 [4 1 7]
 [2 6 0]]
Visitando #12933
Visitando #12934
[[3 0 5]
 [4 8 7]
 [2 1 6]]
[[3 8 5]
 [0 4 7]
 [2 1 6]]
[[3 8 5]
 [4 7 0]
 [2 1 6]]
Visitando #12935
[[3 8 0]
 [4 7 5]
 [2 1 6]]
[[3 8 5]
 [4 7 6]
 [2 1 0]]
Visitando #12936
[[3 8 5]
 [4 7 6]
 [2 0 1]]
Visitando #12937
[[3 8 5]
 [4 0 6]
 [2 7 1]]
[[3 8 5]
 [4 7 6]
 [0 2 1]]
Visitando #12938
[[3 8 5]
 [0 7 6]
 [4 2 1]]
Visitando #12939
[[0 8 5]
 [3 7 6]
 [4 2 1]]
[[3 8 5]
 [7 0 6]
 [4 2 1]]
Visitando #12940
[[3 0 5]
 [7 8 6]
 [4 2 1]]
[[3 8 5]
 [7 2 6]
 [4 0 1]]
[[3 8 5]
 [7 6 0]
 [4